### PR TITLE
New Location for Custom Dockerfiles

### PR DESCRIPTION
**Pull request by LeoKHoward**
New repo for custom Dockerfiles

Trello: https://trello.com/c/fsxEmHqR

### CODE REVIEW

**Comment by LeoKHoward** [comment]
[Create repo for our custom dockerfiles to live (3)](https://trello.com/c/fsxEmHqR/2588-create-repo-for-our-custom-dockerfiles-to-live-3)

**Review by NickGrantONS — CHANGES_REQUESTED** [review]
this repo will store the docker gubbins for multiple images - shouldn't dump stuff in the root. Maybe have a folder per image?

What about a README? Just something to say "put your Dockerfiles in their own directory"

Also would be nice might be a script to build an image, which basically just does `docker build . -t <tag name>`?

**Review by gavinleeedwards — CHANGES_REQUESTED** [review]
Similar comments to Nicks...

- The Dockerfile thats in there now...what is it? what's it used for?
- Each set will need their own directory, otherwise there'll just be a mess of random dockerfiles. It'd be good to record in the README what each set of files are used for, where they're used, maybe how to build them etc.  either in the top level README or one in each directory.

**Review by NickGrantONS — APPROVED** [review]
LGTM 👍

**Review by davidmort — APPROVED** [review]

**Review by gavinleeedwards — APPROVED** [review]

**Pull request merged**
